### ISSUE TITLE
SBW

### ISSUE THREAD

**Issue by zarei673mo** [cran/sbw#1]
akka.actor.InvalidActorNameException: actor name [02a14edfa1edd93f8426b23aaf6e0c5be1e87622adfe547071fa50e23560215964] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130)
	at akka.actor.dungeon.Children$class.reserveChild(Children.scala:76)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:369)
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:201)
	at akka.actor.dungeon.Children$class.attachChild(Children.scala:41)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:369)
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:553)
	at fr.acinq.eclair.blockchain.electrum.ElectrumWallet$.makeSigningWalletParts(ElectrumWallet.scala:285)
	at com.btcontract.wallet.SettingsActivity$$anon$4$$anonfun$2$$anonfun$apply$mcV$sp$1.com$btcontract$wallet$SettingsActivity$$anon$$anonfun$$anonfun$$proceed$1(SettingsActivity.scala:73)
	at com.btcontract.wallet.SettingsActivity$$anon$4$$anonfun$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(SettingsActivity.scala:65)
	at com.btcontract.wallet.SettingsActivity$$anon$4$$anonfun$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(SettingsActivity.scala:65)
	at com.btcontract.wallet.BaseActivity$$anonfun$3.apply$mcV$sp(BaseActivity.scala:252)
	at com.btcontract.wallet.BaseActivity$$anon$6.onClick(BaseActivity.scala:187)
	at android.view.View.performClick(View.java:7569)
	at android.view.View.performClickInternal(View.java:7546)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29738)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
